const PDFDocument = require('pdfkit');

const buildPDF = (req, res) => {
  const { paperData } = req.body;
  const { subject, paper } = paperData;

  const doc = new PDFDocument({ margin: 50 });

  // 1. Set headers so the browser knows a file is coming
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=${subject}_Exam.pdf`);

  // 2. Pipe the PDF into the response
  doc.pipe(res);

  // --- PDF CONTENT STARTS HERE ---

  // UNIVERSITY HEADER (Based on your sample)
  doc.fontSize(10).text(`Printed Pages: 2`, { align: 'right' });
  doc.moveDown(0.5);
  
  doc.fontSize(14).font('Helvetica-Bold').text('B. TECH. (SEM VI) THEORY EXAMINATION', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(12).text(subject.toUpperCase(), { align: 'center' });
  doc.moveDown(1);

  doc.fontSize(10).font('Helvetica').text('Time: 3 Hours                                                                                Total Marks: 100', { align: 'center' });
  doc.text('__________________________________________________________________________', { align: 'center' });
  doc.moveDown(2);

  doc.font('Helvetica').text('Note: Attempt all Sections. If require any missing data; then choose suitably.');
  doc.moveDown(1);

  // --- SECTION A ---
  doc.font('Helvetica-Bold').text('SECTION A', { align: 'center' });
  doc.fontSize(11).text('1. Attempt all questions in brief.', { continued: true });
  doc.text('                                                                      2 x 10 = 20', { align: 'right' });
  doc.moveDown(0.5);

  doc.font('Helvetica').fontSize(11);
  const labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'];
  
  paper.sectionA.forEach((q, index) => {
    // Check if label exists, else use number
    const label = labels[index] || (index + 1);
    doc.text(`${label}.  ${q.question_text}`);
    doc.moveDown(0.5);
  });

  doc.moveDown(1);

  // --- SECTION B ---
  doc.font('Helvetica-Bold').text('SECTION B', { align: 'center' });
  doc.text('2. Attempt any three of the following:', { continued: true });
  doc.text('                                                                     10 x 3 = 30', { align: 'right' });
  doc.moveDown(0.5);

  doc.font('Helvetica');
  const labelsB = ['a', 'b', 'c', 'd', 'e'];
  paper.sectionB.forEach((q, index) => {
    const label = labelsB[index] || (index + 1);
    doc.text(`${label}.  ${q.question_text}`);
    doc.moveDown(0.8);
  });

  doc.moveDown(1);

  // --- SECTION C ---
  doc.font('Helvetica-Bold').text('SECTION C', { align: 'center' });
  doc.text('Attempt any one part of the following:', { align: 'left' });
  doc.text('                                                                                                    10 x 1 = 10', { align: 'right', moveUp: true }); // Align marks to right
  doc.moveDown(1);

  doc.font('Helvetica');
  
  // Section C has pairs of questions (Internal Choice)
  paper.sectionC.forEach((item, index) => {
    const qNum = index + 3; // Starts from Q3, Q4, Q5...
    doc.font('Helvetica-Bold').text(`${qNum}. Attempt any one part of the following:                                           10 x 1 = 10`);
    doc.font('Helvetica');
    
    // Part (a)
    if(item.questions[0]) {
      doc.text(`(a) ${item.questions[0].question_text}`);
    }
    
    // Part (b)
    if(item.questions[1]) {
      doc.moveDown(0.2);
      doc.text(`(b) ${item.questions[1].question_text}`);
    }
    doc.moveDown(1);
  });

  // --- FOOTER ---
  doc.moveDown(2);
  doc.fontSize(8).text('Generated by AI Question Paper System', { align: 'center', color: 'grey' });

  // 3. Finalize PDF
  doc.end();
};

module.exports = { buildPDF };